/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snake;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dominic
 */
public class frmSnake extends javax.swing.JFrame implements KeyListener {

    private SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
    private SimpleDateFormat sdf1 = new SimpleDateFormat("dd/MM/yyyy");
    private boolean run = true;
    String[] optiuniStart = {"Incepe joc nou", "Incepe joc anterior","iesire"};

    /**
     * Creates new form frmSnake
     */
    public frmSnake() {
        initComponents();
        patratel.requestFocusInWindow();
        catchMe.setLocation(100, 100);
        patratel.setLocation(20, 300);
        patratel.setScena(playGround);

        patratel.setMaxX(playGround.getWidth() - PanelulMeu.PATRAT_SIZE);
        patratel.setMaxY(playGround.getHeight() - PanelulMeu.PATRAT_SIZE);
        patratel.setViteza(PanelulMeu.VITEZA_MEDIE);
        patratel.setCatchMe(catchMe);

        Thread thAnimaCeas = new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    lblCeas.setText(sdf.format(System.currentTimeMillis()));
                    lblData.setText(sdf1.format(System.currentTimeMillis()));
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(frmSnake.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        thAnimaCeas.start();

       

      
            Thread thMovePatrat = new Thread(new Runnable() {
                @Override
                public void run() {
                    while (true) {
                        if (run) {
                           
                            patratel.movePatrat();
                            patratel.deseneaza();
                            switch(patratel.getNrVieti()){
                                case 3:
                                    panelulMeu1.setVisible(true);
                                    panelulMeu2.setVisible(true);
                                    panelulMeu3.setVisible(true);
                                    break;
                                case 2:
                                    panelulMeu1.setVisible(true);
                                    panelulMeu2.setVisible(true);
                                    panelulMeu3.setVisible(false);
                                    break;
                                case 1:
                                    panelulMeu1.setVisible(true);
                                    panelulMeu2.setVisible(false);
                                    panelulMeu3.setVisible(false);
                                    break;
                                case 0:
                                    panelulMeu1.setVisible(false);
                                    panelulMeu2.setVisible(false);
                                    panelulMeu3.setVisible(false);
                                    break;
                            }
                            lblScor.setText(String.valueOf(patratel.getNrPuncte()));
                            try {
                                Thread.sleep(patratel.getViteza());

                            } catch (InterruptedException ex) {
                                Logger.getLogger(frmSnake.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } else {
                            try {
                                Thread.sleep(300);
                            } catch (InterruptedException ex) {
                                Logger.getLogger(frmSnake.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }

                }

            });

            thMovePatrat.start();
      

        //   JPanel pornire.remove(this);
        
        Image img = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Dominic\\Desktop\\images.jpg");
        setIconImage(img);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playGround = new javax.swing.JPanel();
        patratel = new ClaseInterfete.PanelulMeu();
        catchMe = new ClaseInterfete.PanelulMeu();
        instrumente = new javax.swing.JPanel();
        lblCeas = new javax.swing.JLabel();
        btnPauzaJoc = new javax.swing.JButton();
        lblPunctaj = new javax.swing.JLabel();
        lblScor = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelulMeu1 = new ClaseInterfete.PanelulMeu();
        panelulMeu2 = new ClaseInterfete.PanelulMeu();
        panelulMeu3 = new ClaseInterfete.PanelulMeu();
        lblRestart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snake");

        playGround.setBackground(new java.awt.Color(153, 255, 0));
        playGround.setLayout(null);

        javax.swing.GroupLayout patratelLayout = new javax.swing.GroupLayout(patratel);
        patratel.setLayout(patratelLayout);
        patratelLayout.setHorizontalGroup(
            patratelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        patratelLayout.setVerticalGroup(
            patratelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        playGround.add(patratel);
        patratel.setBounds(40, 40, 20, 20);

        catchMe.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout catchMeLayout = new javax.swing.GroupLayout(catchMe);
        catchMe.setLayout(catchMeLayout);
        catchMeLayout.setHorizontalGroup(
            catchMeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        catchMeLayout.setVerticalGroup(
            catchMeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        playGround.add(catchMe);
        catchMe.setBounds(380, 180, 20, 20);

        instrumente.setBackground(new java.awt.Color(255, 255, 0));

        lblCeas.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblCeas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCeas.setText("jLabel1    ");

        btnPauzaJoc.setText("Pauza joc");
        btnPauzaJoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauzaJocActionPerformed(evt);
            }
        });

        lblPunctaj.setText("Nr. de puncte:   ");

        lblScor.setText("jLabel1");

        lblData.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblData.setText("  jLabel1");

        jLabel1.setText("Nr. de vieti:");

        panelulMeu1.setBackground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout panelulMeu1Layout = new javax.swing.GroupLayout(panelulMeu1);
        panelulMeu1.setLayout(panelulMeu1Layout);
        panelulMeu1Layout.setHorizontalGroup(
            panelulMeu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        panelulMeu1Layout.setVerticalGroup(
            panelulMeu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        panelulMeu2.setBackground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout panelulMeu2Layout = new javax.swing.GroupLayout(panelulMeu2);
        panelulMeu2.setLayout(panelulMeu2Layout);
        panelulMeu2Layout.setHorizontalGroup(
            panelulMeu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        panelulMeu2Layout.setVerticalGroup(
            panelulMeu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        panelulMeu3.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout panelulMeu3Layout = new javax.swing.GroupLayout(panelulMeu3);
        panelulMeu3.setLayout(panelulMeu3Layout);
        panelulMeu3Layout.setHorizontalGroup(
            panelulMeu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        panelulMeu3Layout.setVerticalGroup(
            panelulMeu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        lblRestart.setText("Restart joc");
        lblRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblRestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout instrumenteLayout = new javax.swing.GroupLayout(instrumente);
        instrumente.setLayout(instrumenteLayout);
        instrumenteLayout.setHorizontalGroup(
            instrumenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrumenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(instrumenteLayout.createSequentialGroup()
                        .addComponent(lblPunctaj, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblScor))
                    .addGroup(instrumenteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelulMeu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelulMeu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelulMeu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(instrumenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRestart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPauzaJoc, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addGroup(instrumenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(instrumenteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblCeas, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, instrumenteLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        instrumenteLayout.setVerticalGroup(
            instrumenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrumenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCeas)
                    .addComponent(btnPauzaJoc)
                    .addComponent(lblPunctaj, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblScor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(instrumenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(instrumenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblData)
                        .addComponent(jLabel1)
                        .addComponent(lblRestart))
                    .addComponent(panelulMeu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelulMeu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelulMeu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playGround, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addComponent(instrumente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(playGround, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(instrumente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPauzaJocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauzaJocActionPerformed
        // TODO add your handling code here:
        if (run) {
            run = false;
            btnPauzaJoc.setText("Reincepe joc");
            
        } else {
            run = true;
            patratel.requestFocusInWindow();
            btnPauzaJoc.setText("Pauza joc");
        }

    }//GEN-LAST:event_btnPauzaJocActionPerformed

    private void lblRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblRestartActionPerformed
        // TODO add your handling code here:
        patratel.restartJoc();
        playGround.validate();
        playGround.updateUI();
        
    }//GEN-LAST:event_lblRestartActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPauzaJoc;
    private ClaseInterfete.PanelulMeu catchMe;
    private javax.swing.JPanel instrumente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCeas;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblPunctaj;
    private javax.swing.JButton lblRestart;
    private javax.swing.JLabel lblScor;
    private ClaseInterfete.PanelulMeu panelulMeu1;
    private ClaseInterfete.PanelulMeu panelulMeu2;
    private ClaseInterfete.PanelulMeu panelulMeu3;
    private ClaseInterfete.PanelulMeu patratel;
    private javax.swing.JPanel playGround;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyReleased(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
