/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package salaCinema.gui;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import salaCinema.Film;
import salaCinema.FilmService;

/**
 *
 * @author Dominic
 */
public class frmAdaugaEditeazaDateFilm extends javax.swing.JDialog {

    /**
     * Creates new form frmAdaugaEditeazaDateFilm
     */
    public frmAdaugaEditeazaDateFilm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumeFilm = new javax.swing.JLabel();
        txtNumeFilm = new javax.swing.JTextField();
        lblDurata = new javax.swing.JLabel();
        spnDurataFilm = new javax.swing.JSpinner();
        lblDataInceput = new javax.swing.JLabel();
        lblPret = new javax.swing.JLabel();
        spnPret = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        spnZileRulare = new javax.swing.JSpinner();
        btnSalvareDateFilm = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNumeFilm.setText("Nume film :");

        lblDurata.setText("Durata :");

        spnDurataFilm.setModel(new javax.swing.SpinnerNumberModel(80, 0, 250, 1));

        lblDataInceput.setText("Data inceput rulare :");

        lblPret.setText("Pret :");

        spnPret.setModel(new javax.swing.SpinnerNumberModel(10, 10, 35, 5));

        jLabel1.setText("Numar zile de rulare :");

        spnZileRulare.setModel(new javax.swing.SpinnerNumberModel(3, 3, 30, 1));

        btnSalvareDateFilm.setText("Salveaza date film");
        btnSalvareDateFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvareDateFilmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPret)
                            .addComponent(lblDataInceput)
                            .addComponent(lblDurata)
                            .addComponent(lblNumeFilm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeFilm)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnDurataFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spnPret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(spnZileRulare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 66, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvareDateFilm)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeFilm)
                    .addComponent(txtNumeFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDurata)
                    .addComponent(spnDurataFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataInceput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(spnPret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(spnZileRulare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPret))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvareDateFilm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvareDateFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvareDateFilmActionPerformed
        // TODO add your handling code here:
        String numeFilm = txtNumeFilm.getText().trim();
        
        if(numeFilm.length() < 3){
            JOptionPane.showMessageDialog(this, "Numele filmului trebuie sa contina minim 3 caractere", "Eroare nume film!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int durataFilm = Integer.parseInt(spnDurataFilm.getValue().toString());
        int pret = Integer.parseInt(spnPret.getValue().toString());
        int nrZileRulare = Integer.parseInt(spnZileRulare.getValue().toString());
        Date dataInceputRulare = dateChooser.getDate();
        if(dataInceputRulare == null){
            JOptionPane.showMessageDialog(this, "Introduceti o data", "Eroare data!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Film filmf = new Film(numeFilm, durataFilm, pret);
        
        filmf.setDataInceput(dataInceputRulare);
        filmf.setNrZileRulare(nrZileRulare);
        
        FilmService fs = new FilmService();
        try {
            
            ArrayList<Film> listaFilmeFisier=fs.getListaFilmeDinFisier();
            listaFilmeFisier.add(filmf);
            fs.salveazaDateFilme(listaFilmeFisier);
            JOptionPane.showMessageDialog(this, "Filmul s-a salvat in fisier", "Film Salvat", JOptionPane.INFORMATION_MESSAGE);
            
            
            
        } catch (IOException ex) {
            Logger.getLogger(frmAdaugaEditeazaDateFilm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_btnSalvareDateFilmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdaugaEditeazaDateFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdaugaEditeazaDateFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdaugaEditeazaDateFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdaugaEditeazaDateFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmAdaugaEditeazaDateFilm dialog = new frmAdaugaEditeazaDateFilm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvareDateFilm;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDataInceput;
    private javax.swing.JLabel lblDurata;
    private javax.swing.JLabel lblNumeFilm;
    private javax.swing.JLabel lblPret;
    private javax.swing.JSpinner spnDurataFilm;
    private javax.swing.JSpinner spnPret;
    private javax.swing.JSpinner spnZileRulare;
    private javax.swing.JTextField txtNumeFilm;
    // End of variables declaration//GEN-END:variables
}
