/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salaCinema.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import salaCinema.Sala;

/**
 *
 * @author Dominic
 */
public class frmConfigurareSala extends javax.swing.JDialog {
    
    private int [][] configSala;
    private Sala sala;
    /**
     * Creates new form frmConfigurareSala
     */
    public frmConfigurareSala(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblDetaliiLocuriConfigurate.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNrLocuri = new javax.swing.JLabel();
        spnNumarLocuri = new javax.swing.JSpinner();
        btnGenereazaSala = new javax.swing.JButton();
        panelSala = new javax.swing.JPanel();
        btnSalveazaConfiguratieSala = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblDetaliiLocuriConfigurate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cinema 3D Calarasi");

        lblNrLocuri.setText("Dati numar locuri :");

        spnNumarLocuri.setModel(new javax.swing.SpinnerNumberModel(20, 16, 500, 1));

        btnGenereazaSala.setText("Genereaza sala");
        btnGenereazaSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenereazaSalaActionPerformed(evt);
            }
        });

        panelSala.setLayout(new java.awt.GridLayout(1, 0));

        btnSalveazaConfiguratieSala.setText("Salveaza configuratie sala");
        btnSalveazaConfiguratieSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalveazaConfiguratieSalaActionPerformed(evt);
            }
        });

        lblDetaliiLocuriConfigurate.setText("Locuri configurate 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDetaliiLocuriConfigurate, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDetaliiLocuriConfigurate)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNrLocuri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnNumarLocuri, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGenereazaSala)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(btnSalveazaConfiguratieSala, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNrLocuri)
                    .addComponent(spnNumarLocuri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenereazaSala))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSala, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalveazaConfiguratieSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenereazaSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenereazaSalaActionPerformed
        // TODO add your handling code here:
        lblDetaliiLocuriConfigurate.setVisible(true);
        int nrLocuri = Integer.parseInt(spnNumarLocuri.getValue().toString());

        sala = new Sala(nrLocuri, "Cinema calarasi");
        int nrLC = sala.getNrLiniiColoane();
        //    System.out.println(nrLC);
        ((GridLayout) (panelSala.getLayout())).setColumns(nrLC);
        ((GridLayout) (panelSala.getLayout())).setRows(nrLC);
        panelSala.removeAll();
        for (int i = 0; i < nrLC; i++) {
            for (int j = 0; j < nrLC; j++) {

                CustomJLabelLocInSala locInSala = new CustomJLabelLocInSala(sala.getSala(), i, j);
                //JButton locInSala=new JButton();
                //locInSala.setBackground(Color.RED);
                locInSala.setBorder(BorderFactory.createLineBorder(Color.yellow));
                locInSala.setOpaque(true);
                panelSala.add(locInSala);
            }
        }

        panelSala.updateUI();
        panelSala.validate();

    }//GEN-LAST:event_btnGenereazaSalaActionPerformed

    private void btnSalveazaConfiguratieSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalveazaConfiguratieSalaActionPerformed
        // TODO add your handling code here:
        int nrLocuri = Integer.parseInt(spnNumarLocuri.getValue().toString());
        configSala = sala.getSala();
        int nrLC = sala.getNrLiniiColoane();
        
        int nrDisponibile = 0;
        for (int i = 0; i < configSala.length; i++) {
            for (int j = 0; j < configSala.length; j++) {
                if (configSala[i][j] == 0) {
                    nrDisponibile=nrDisponibile+1;
                    
                }    
                
                
            
            }
        }
        System.out.println(nrLocuri);
        for(int i = 0; i<configSala.length;i++){
            for(int j = 0; j<configSala.length; j++){
                System.out.print(configSala[i][j]+" ");
            }
            System.out.println();
        }
        
        System.out.println(nrDisponibile);
           if(nrDisponibile != nrLocuri){
                     JOptionPane.showMessageDialog(this, "-Selectati exact numarul de locuri pe care l-ati precizat-", "Eroare numar locuri!", JOptionPane.ERROR_MESSAGE);
                     return;
                }
           
        //   public void salveazaDateFisier() throws IOException {
        PrintWriter pw=null;
        try {
            pw = new PrintWriter(new FileWriter("C:\\Users\\Dominic\\Desktop\\config_sala.txt"));
        } catch (IOException ex) {
            Logger.getLogger(frmConfigurareSala.class.getName()).log(Level.SEVERE, null, ex);
        }
        pw.println(sala.getNrLiniiColoane());
        for (int i = 0; i < nrLC; i++) {
            for (int j = 0; j < nrLC; j++) {
                pw.print(sala.getSala()[i][j] + "|");
            }
            pw.println();
        }
        pw.close();

    //}
           
           
              
    }//GEN-LAST:event_btnSalveazaConfiguratieSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConfigurareSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConfigurareSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConfigurareSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConfigurareSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmConfigurareSala dialog = new frmConfigurareSala(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenereazaSala;
    private javax.swing.JButton btnSalveazaConfiguratieSala;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDetaliiLocuriConfigurate;
    private javax.swing.JLabel lblNrLocuri;
    private javax.swing.JPanel panelSala;
    private javax.swing.JSpinner spnNumarLocuri;
    // End of variables declaration//GEN-END:variables
}
