/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import beans.Elevi;
import dao.EleviDAO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import obiecte.Elev;
import utils.EleviManager;

/**
 *
 * @author Dominic
 */
public class frmAdministrareElev extends javax.swing.JDialog {

    /**
     * Creates new form frmAdministrareElev
     */
    private EleviDAO em = new EleviDAO();
    private DefaultListModel model;
    private List<Elevi> listaElevi;
    
    public frmAdministrareElev(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listaElevi = em.getListaElevi();
        model = new DefaultListModel();
        //  List<Elev> listeElevi = em.getListaElevi();
        for (int i = 0; i < listaElevi.size(); i++) {
            model.addElement(listaElevi.get(i));
        }
        
        jList.setModel(model);
        
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdaugaElevi = new javax.swing.JButton();
        btnEditeazaElev = new javax.swing.JButton();
        btnStergeElev = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrare elevi");

        btnAdaugaElevi.setText("Adauga elev");
        btnAdaugaElevi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdaugaEleviActionPerformed(evt);
            }
        });

        btnEditeazaElev.setText("Editeaza elev");
        btnEditeazaElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditeazaElevActionPerformed(evt);
            }
        });

        btnStergeElev.setText("Sterge elev");
        btnStergeElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStergeElevActionPerformed(evt);
            }
        });

        jList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStergeElev, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdaugaElevi, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditeazaElev, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdaugaElevi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnEditeazaElev, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStergeElev, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdaugaEleviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdaugaEleviActionPerformed
        // TODO add your handling code here:
        frmAdaugaElevi frmADELEV = new frmAdaugaElevi(this, true, null, em);
        frmADELEV.setDf(model);
        frmADELEV.setVisible(true);
        

    }//GEN-LAST:event_btnAdaugaEleviActionPerformed

    private void btnEditeazaElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditeazaElevActionPerformed
        Elevi e = (Elevi) jList.getSelectedValue();
        if (e == null) {
            JOptionPane.showMessageDialog(this, "Pentru a edita, va rog selectati un elev", "Editare elev", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        frmAdaugaElevi frmAM = new frmAdaugaElevi(this, true, e, em);
        frmAM.setDf(model);
        frmAM.setVisible(true);
        

    }//GEN-LAST:event_btnEditeazaElevActionPerformed

    private void btnStergeElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStergeElevActionPerformed
        // TODO add your handling code here:
        int index = jList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Va rog, selectati o materie!", "Eroare elev", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int raspuns = JOptionPane.showConfirmDialog(this, "Sigur vreti sa stergeti elevul din catalog?", "Stergere elev", JOptionPane.YES_NO_OPTION);
        if (raspuns == JOptionPane.YES_OPTION) {
            em.removeElev((Elevi) jList.getSelectedValue());
            model.remove(index);
            
        }
        

    }//GEN-LAST:event_btnStergeElevActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdaugaElevi;
    private javax.swing.JButton btnEditeazaElev;
    private javax.swing.JButton btnStergeElev;
    private javax.swing.JList jList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
