/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.util.Date;
import java.util.List;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import obiecte.Absenta;
import obiecte.Elev;
import obiecte.Materie;
import obiecte.Nota;
import obiecte.Profesor;
import tablemodel.AbsenteTableModel;
import utils.AbsenteManager;
import utils.EleviManager;
import utils.MateriiManager;
import utils.NoteManager;
import utils.ProfManager;

/**
 *
 * @author Dominic
 */
public class frmAdaugaAbsenta extends javax.swing.JDialog {

    /**
     * Creates new form frmAdaugaAbsenta
     */
     private MateriiManager materiiManager = new MateriiManager();
    private ProfManager pm = new ProfManager();
    private EleviManager em = new EleviManager();
    private AbsenteManager ab = new AbsenteManager();
    private AbsenteTableModel absenteTableModel;
    
    
    public frmAdaugaAbsenta(JDialog other, boolean modal) {
        super(other, modal);
        initComponents();
        DefaultComboBoxModel materiiModel = new DefaultComboBoxModel();
        materiiModel.addElement("--Selectati materia--");
        List<Materie> materii = materiiManager.getListaMaterii();
        for (Materie m : materii) {
            materiiModel.addElement(m);
        }

        cmbMaterie.setModel(materiiModel);
        DefaultComboBoxModel profesoriModel = new DefaultComboBoxModel();
        profesoriModel.addElement("--Selectati profesor--");
        List<Profesor> profesori = pm.getListaProfesori();
        for (Profesor p : profesori) {
            profesoriModel.addElement(p);
        }
        cmbProfesori.setModel(profesoriModel);
        DefaultComboBoxModel eleviModel = new DefaultComboBoxModel();
        eleviModel.addElement("--Selectati elev--");
        List<Elev> elevi = em.getListaElevi();
        for (Elev e : elevi) {
            eleviModel.addElement(e);
        }
        cmbElev.setModel(eleviModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        cmbProfesori = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbMaterie = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbElev = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        dataChooser = new com.toedter.calendar.JDateChooser();
        btnSalveazaAbsenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adauga absenta");

        jPanel1.setName("Adauga absenta"); // NOI18N

        jLabel1.setText("Absenta :");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("motivata");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButton1.setName(""); // NOI18N

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("nemotivata");

        jLabel2.setText("Profesor :");

        cmbProfesori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Materie :");

        cmbMaterie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Elev :");

        cmbElev.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("data/ora nota :");

        btnSalveazaAbsenta.setText("Salveaza date");
        btnSalveazaAbsenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalveazaAbsentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jRadioButton1)
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButton2))
                        .addComponent(cmbProfesori, 0, 276, Short.MAX_VALUE)
                        .addComponent(cmbMaterie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbElev, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(dataChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalveazaAbsenta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbProfesori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMaterie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbElev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addComponent(btnSalveazaAbsenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("Detalii absenta");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalveazaAbsentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalveazaAbsentaActionPerformed

        // TODO add your handling code here:
        
        if (!valid()) {
            return;
        }
        Profesor p = (Profesor) cmbProfesori.getSelectedItem();
        Materie m = (Materie) cmbMaterie.getSelectedItem();
        Elev e = (Elev) cmbElev.getSelectedItem();
        Date d = dataChooser.getDate();
        
        Absenta a = new Absenta(d, e, m,jRadioButton1.isSelected(), p);
        ab.saveAbsenta(a);
        JOptionPane.showMessageDialog(this, "Absenta a fost salvata", "Salvare absenta", JOptionPane.INFORMATION_MESSAGE);
        absenteTableModel.adaugaAbsenta(a);
        dispose();
        
    }//GEN-LAST:event_btnSalveazaAbsentaActionPerformed

    
    private boolean valid() {
        if (cmbProfesori.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Va rog, selectati un profesor din lista", "Eroare profesor", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }

        if (cmbMaterie.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Va rog, selectati o materie din lista", "Eroare materie", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (cmbElev.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Va rog, selectati un elev din lista", "Eroare elev", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (dataChooser.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Va rog, selectati data si ora ", "Eroare data", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }

        return true;

    }
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalveazaAbsenta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbElev;
    private javax.swing.JComboBox cmbMaterie;
    private javax.swing.JComboBox cmbProfesori;
    private com.toedter.calendar.JDateChooser dataChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables


    public void setAbsenteTableModel(AbsenteTableModel atm){
        this.absenteTableModel = atm;
    }
}