/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Profesori;
import dao.ProfesoriDAO;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import obiecte.Profesor;
import utils.ProfManager;

/**
 *
 * @author Dominic
 */
public class frmAdministrareProfesor extends javax.swing.JDialog {

    private DefaultListModel dlmodel;
    private ProfesoriDAO pd = new ProfesoriDAO();
    private List<Profesori> listaProfesori;
    

    /**
     * Creates new form frmAdministrareProfesor
     */
    public frmAdministrareProfesor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dlmodel = new DefaultListModel();
            List<Profesori> listaProfesori = pd.getListaProfesori();
            for (int i = 0; i < listaProfesori.size(); i++) {
                dlmodel.addElement(listaProfesori.get(i));
            }
        

        JlistaProfesori.setModel(dlmodel);

        setLocationRelativeTo(parent);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditeazaProfesor = new javax.swing.JButton();
        btnAdaugaProfesori = new javax.swing.JButton();
        btnStergeProfesor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JlistaProfesori = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrare profesori");

        btnEditeazaProfesor.setText("Editeaza profesor");
        btnEditeazaProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditeazaProfesorActionPerformed(evt);
            }
        });

        btnAdaugaProfesori.setText("Adauga profesor");
        btnAdaugaProfesori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdaugaProfesoriActionPerformed(evt);
            }
        });

        btnStergeProfesor.setText("Sterge profesor");
        btnStergeProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStergeProfesorActionPerformed(evt);
            }
        });

        JlistaProfesori.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(JlistaProfesori);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStergeProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditeazaProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdaugaProfesori, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdaugaProfesori, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnEditeazaProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(btnStergeProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdaugaProfesoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdaugaProfesoriActionPerformed
        // TODO add your handling code here:
        frmAdaugaProfesor frmAP = new frmAdaugaProfesor(this, true, null, pd);
        frmAP.setDf(dlmodel);
        frmAP.setVisible(true);

    }//GEN-LAST:event_btnAdaugaProfesoriActionPerformed

    private void btnEditeazaProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditeazaProfesorActionPerformed
        // TODO add your handling code here:
        Profesori p = (Profesori) JlistaProfesori.getSelectedValue();
        if(p==null){
            JOptionPane.showMessageDialog(this, "Va rog, selectati un profesor", "Profesor neselectat", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        frmAdaugaProfesor frmAP = new frmAdaugaProfesor(this, true, p, pd);
        frmAP.setDf(dlmodel);
        frmAP.setVisible(true);
        
        
        
    }//GEN-LAST:event_btnEditeazaProfesorActionPerformed

    private void btnStergeProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStergeProfesorActionPerformed
        // TODO add your handling code here:
        int ind = JlistaProfesori.getSelectedIndex();
        if(ind == -1){
            JOptionPane.showMessageDialog(this, "Va rog, selectati un profesor", "Profesor neselectat", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int raspuns = JOptionPane.showConfirmDialog(this, "Sigur vreti sa stergeti materia?", "stergere materie", JOptionPane.YES_NO_OPTION);
        if(raspuns == JOptionPane.YES_OPTION){
           dlmodel.remove(ind);
           pd.removeProfesor((Profesori) JlistaProfesori.getSelectedValue());
           pd.getListaProfesori();
        }
        
    }//GEN-LAST:event_btnStergeProfesorActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList JlistaProfesori;
    private javax.swing.JButton btnAdaugaProfesori;
    private javax.swing.JButton btnEditeazaProfesor;
    private javax.swing.JButton btnStergeProfesor;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
