/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import obiecte.Absenta;
import obiecte.Nota;
import utils.NoteManager;

/**
 *
 * @author Dominic
 */
public class frmAdministrareNote extends javax.swing.JDialog {

    /**
     * Creates new form frmAdministrareNote
     */
    
   
    
    private NoteManager noteManager=new NoteManager();
    public frmAdministrareNote(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        noteTableModel1.setListaNote(noteManager.getListaNote());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noteTableModel1 = new tablemodel.NoteTableModel();
        scrllNote = new javax.swing.JScrollPane();
        tableNote = new javax.swing.JTable();
        btnAdaugaNote = new javax.swing.JButton();
        btnStergeNote = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrare note");

        tableNote.setModel(noteTableModel1);
        scrllNote.setViewportView(tableNote);

        btnAdaugaNote.setText("Adauga note");
        btnAdaugaNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdaugaNoteActionPerformed(evt);
            }
        });

        btnStergeNote.setText("Sterge note");
        btnStergeNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStergeNoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrllNote, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdaugaNote, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStergeNote, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdaugaNote, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btnStergeNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrllNote, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdaugaNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdaugaNoteActionPerformed
        // TODO add your handling code here:
        
        frmAdaugaNota frm=new frmAdaugaNota(this,true);
        frm.setNoteTableModel(noteTableModel1);
        frm.setLocationRelativeTo(this);
        frm.setVisible(true);
        
    }//GEN-LAST:event_btnAdaugaNoteActionPerformed

    private void btnStergeNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStergeNoteActionPerformed
        int index=tableNote.convertRowIndexToModel(tableNote.getSelectedRow());
        if(index!=-1){
            int raspuns=JOptionPane.showConfirmDialog(this, "Sigur stergeti nota ?", "Stergere nota",JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE);
            if(raspuns==JOptionPane.YES_OPTION){
                Nota n=noteTableModel1.getNota(index);
                noteManager.removeNota(n);
                noteTableModel1.removeNota(n);
                JOptionPane.showMessageDialog(this,"Nota stearsa cu succes!");
            }
            
        }else{
                JOptionPane.showMessageDialog(this, "Va rog selectati o nota", "Stergere nota", JOptionPane.INFORMATION_MESSAGE);
            }
        
    }//GEN-LAST:event_btnStergeNoteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdaugaNote;
    private javax.swing.JButton btnStergeNote;
    private tablemodel.NoteTableModel noteTableModel1;
    private javax.swing.JScrollPane scrllNote;
    private javax.swing.JTable tableNote;
    // End of variables declaration//GEN-END:variables
}
