/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Elevi;
import dao.EleviDAO;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JOptionPane;
import obiecte.Elev;

/**
 *
 * @author Dominic
 */
public class frmAdaugaElevi extends javax.swing.JDialog {

    /**
     * Creates new form frmAdaugaElevi
     */
    private EleviDAO elManager;
    private DefaultListModel df;
    private final Elevi elevSelectat;

    public frmAdaugaElevi(JDialog parent, boolean modal, Elevi e, EleviDAO el) {
        super(parent, modal);
        initComponents();
        this.elevSelectat = e;
        this.elManager = el;
        if (elevSelectat != null) {
            initalizareControaleGraficeCuDateleElevului(elevSelectat);
        }
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNume = new javax.swing.JLabel();
        lblPrenume = new javax.swing.JLabel();
        lblCNP = new javax.swing.JLabel();
        lblAdresa = new javax.swing.JLabel();
        lblClasa = new javax.swing.JLabel();
        btnAdaugaElev = new javax.swing.JButton();
        txtNume = new javax.swing.JTextField();
        txtPrenume = new javax.swing.JTextField();
        txtCNP = new javax.swing.JTextField();
        cmbNumarClasa = new javax.swing.JComboBox();
        cmbLiteraClasa = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAdresa = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adauga Elevi");

        lblNume.setText("Nume :");

        lblPrenume.setText("Prenume :");

        lblCNP.setText("CNP :");

        lblAdresa.setText("Adresa :");

        lblClasa.setText("Clasa :");

        btnAdaugaElev.setText("Adauga elev");
        btnAdaugaElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdaugaElevActionPerformed(evt);
            }
        });

        cmbNumarClasa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Selectati clasa--", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII" }));

        cmbLiteraClasa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Selectati litera clasei--", "A", "B", "C", "D", "E", "F", "G", "H" }));

        txtAdresa.setColumns(20);
        txtAdresa.setRows(5);
        jScrollPane1.setViewportView(txtAdresa);

        jLabel1.setText("adresa ex: str. --------, nr. --, oras. --------, cod postal -------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClasa)
                    .addComponent(lblAdresa)
                    .addComponent(lblCNP)
                    .addComponent(lblPrenume)
                    .addComponent(lblNume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbNumarClasa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbLiteraClasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(txtNume)
                    .addComponent(txtPrenume)
                    .addComponent(txtCNP, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdaugaElev, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNume)
                    .addComponent(txtNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrenume)
                    .addComponent(txtPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCNP)
                    .addComponent(txtCNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblAdresa)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClasa)
                    .addComponent(cmbNumarClasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLiteraClasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnAdaugaElev, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setDf(DefaultListModel df) {
        this.df = df;
    }

    private void btnAdaugaElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdaugaElevActionPerformed
        // TODO add your handling code here:
        //txtAdresa.setText("str. ");

        if (!valid()) {
            return;
        }

        String nume = txtNume.getText().trim().toUpperCase();
        String prenume = txtPrenume.getText().trim().toUpperCase();
        String cnp = txtCNP.getText();
        String adresa = txtAdresa.getText();
        String nrClasa = cmbNumarClasa.getSelectedItem().toString();
        String litClasa = cmbLiteraClasa.getSelectedItem().toString();

        String clasa = nrClasa + "-" + litClasa;

        Elevi e = new Elevi();
        e.setNume(nume);
        e.setPrenume(prenume);
        e.setCnp(cnp);
        e.setAdresa(adresa);

        if (elevSelectat != null) {
            e.setId(elevSelectat.getId());
        }

        //e.setNumarClasa(nrClasa);
        //e.setLiteraClasa(litClasa);
        elManager.saveElev(e);
        dispose();
        if (elevSelectat != null) {
            int index = elManager.getElevIndexById(elevSelectat.getId());
            df.set(index, e);
        } else {
            df.addElement(e);
        }

        //String des = nume + "\n" + prenume + "\n" + cnp + "\n" + adresa + "\nClasa a "+nrClasa+"-a "+litClasa;
        String atent = "Elevul a fost salvat";
        JOptionPane.showMessageDialog(this, atent, "Info", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_btnAdaugaElevActionPerformed

    private boolean isCnpValid() {
        String cnp = txtCNP.getText().trim();
        if (cnp.length() != 13) {
            System.out.println("lungime incorecta");
            return false;
        }
        try {
            long l = Long.parseLong(cnp);
        } catch (NumberFormatException ex) {
            System.out.println(ex.getMessage());
            return false;
        }

        char c = cnp.charAt(0);
        System.out.println(c);
        if (c != '1' && c != '2' && c != '5' && c != '6') {
            System.out.println("Cnp invalid dupa primul nr");
            return false;
        }

        return true;

    }

    private boolean valid() {
        String nume = txtNume.getText().trim();
        String prenume = txtPrenume.getText().trim();

        if (nume.length() < 3) {
            JOptionPane.showMessageDialog(this, "Numele trebuie sa aiba minim 3 litere!", "Eroare nume!", JOptionPane.ERROR_MESSAGE);
            txtNume.requestFocusInWindow();
            txtNume.selectAll();
            return false;
        }
        if (prenume.length() < 3) {
            JOptionPane.showMessageDialog(this, "Prenumele trebuie sa aiba minim 3 litere!", "Eroare prenume!", JOptionPane.ERROR_MESSAGE);
            txtPrenume.requestFocusInWindow();
            txtPrenume.selectAll();
            return false;
        }
        if (!isCnpValid()) {
            JOptionPane.showMessageDialog(this, "Cnp-ul nu este valid!", "Eroare Cnp!", JOptionPane.ERROR_MESSAGE);
            txtCNP.requestFocusInWindow();
            txtCNP.selectAll();
            return false;
        }
        if (cmbNumarClasa.getSelectedIndex() == 0 || cmbLiteraClasa.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Selectati o clasa", "Eroare clasa!", JOptionPane.ERROR_MESSAGE);
            cmbNumarClasa.requestFocusInWindow();
            cmbLiteraClasa.requestFocusInWindow();
            return false;
        }
        //daca elevSelectat este null, sunt in formularul de adaugare
        //daca sunt in formularul de editare...ar trebui daca am acelasi cnp cu al elevului
        if ((elevSelectat == null || !elevSelectat.getCnp().equals(txtCNP.getText().trim())) && elManager.isElevExists(txtCNP.getText().trim())) {
        //if(elevSelectat==null && elManager.isElevExists(txtCNP.getText().trim())){ 
        JOptionPane.showMessageDialog(this, "Elevul se afla deja in lista", "eroare elev", JOptionPane.ERROR_MESSAGE);
            txtCNP.requestFocusInWindow();
            txtCNP.selectAll();
            return false;
        }

        return true;
    }

    private JList lista;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdaugaElev;
    private javax.swing.JComboBox cmbLiteraClasa;
    private javax.swing.JComboBox cmbNumarClasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdresa;
    private javax.swing.JLabel lblCNP;
    private javax.swing.JLabel lblClasa;
    private javax.swing.JLabel lblNume;
    private javax.swing.JLabel lblPrenume;
    private javax.swing.JTextArea txtAdresa;
    private javax.swing.JTextField txtCNP;
    private javax.swing.JTextField txtNume;
    private javax.swing.JTextField txtPrenume;
    // End of variables declaration//GEN-END:variables

    private void initalizareControaleGraficeCuDateleElevului(Elevi elevSelectat) {
        txtNume.setText(elevSelectat.getNume());
        txtPrenume.setText(elevSelectat.getPrenume());
        txtCNP.setText(elevSelectat.getCnp());
        txtAdresa.setText(elevSelectat.getAdresa());
        btnAdaugaElev.setText("Salveaza date elev");
        //cmbNumarClasa.setSelectedItem(elevSelectat.getNrClasa());
        //  System.out.println(elevSelectat.getNrClasa());
        //cmbLiteraClasa.setSelectedItem(elevSelectat.getLitClasa());
        //   System.out.println(elevSelectat.getLitClasa());
    }
}
