/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Materii;
import dao.MateriiDAO;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import obiecte.Materie;
import utils.MateriiManager;

/**
 *
 * @author Dominic
 */
public class frmAdministrareMaterie extends javax.swing.JDialog {

    /**
     * Creates new form frmAdministrareMaterie
     */
    //private MateriiManager mm = new MateriiManager();
    private MateriiDAO mm=new MateriiDAO();
    private List<Materii> listaMaterii;
    private DefaultListModel model;

    public frmAdministrareMaterie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
            initComponents();
            setLocationRelativeTo(parent);
            listaMaterii = mm.getListaMaterii();
            model = new DefaultListModel();
            for (int i = 0; i < listaMaterii.size(); i++) {
                model.addElement(listaMaterii.get(i));
            }
            listMaterii.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listMaterii = new javax.swing.JList();
        btnAdauga = new javax.swing.JButton();
        btnEditeazaMaterie = new javax.swing.JButton();
        btnSterge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrare materie");

        listMaterii.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listMaterii.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listMateriiAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(listMaterii);

        btnAdauga.setText("Adauga");
        btnAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdaugaActionPerformed(evt);
            }
        });

        btnEditeazaMaterie.setText("Editeaza");
        btnEditeazaMaterie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditeazaMaterieActionPerformed(evt);
            }
        });

        btnSterge.setText("Sterge");
        btnSterge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStergeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSterge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdauga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditeazaMaterie, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdauga, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(btnEditeazaMaterie, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnSterge, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listMateriiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listMateriiAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_listMateriiAncestorAdded

    private void btnAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdaugaActionPerformed
        // TODO add your handling code here:
        frmAdaugaMaterie frmAM = new frmAdaugaMaterie(this, true, null,mm);
        frmAM.setDf(model); 
        frmAM.setVisible(true);   
          
    }//GEN-LAST:event_btnAdaugaActionPerformed

    private void btnEditeazaMaterieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditeazaMaterieActionPerformed
       Materii m = (Materii) listMaterii.getSelectedValue();
        if(m == null){
            JOptionPane.showMessageDialog(this, "Selectati cel putin o materie", "Eroare materie", JOptionPane.ERROR_MESSAGE);
            return;
        }
      //  System.out.println(m.getNumeMaterie());
        frmAdaugaMaterie frmAM = new frmAdaugaMaterie(this, true, m,mm);
        frmAM.setDf(model);
        frmAM.setMaterieSelectata(m);
        frmAM.setVisible(true);
        
        
        
        
        
        
    }//GEN-LAST:event_btnEditeazaMaterieActionPerformed

    private void btnStergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStergeActionPerformed
        // TODO add your handling code here:
        int index = listMaterii.getSelectedIndex();
        if(index == -1){
            JOptionPane.showMessageDialog(this, "Va rog, selectati o materie!", "Eroare materie", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int raspuns = JOptionPane.showConfirmDialog(this, "Sigur vreti sa stergeti materia?", "Stergere materie", JOptionPane.YES_NO_OPTION);
        if(raspuns == JOptionPane.YES_OPTION){
            model.remove(index);
            mm.removeMaterie(index);
            //mm.saveListaMaterii();
        }
        
        
        
    }//GEN-LAST:event_btnStergeActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdauga;
    private javax.swing.JButton btnEditeazaMaterie;
    private javax.swing.JButton btnSterge;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listMaterii;
    // End of variables declaration//GEN-END:variables
}
