/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.JobAttributes;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import obiecte.Elev;
import obiecte.Materie;
import obiecte.Nota;
import obiecte.Profesor;
import tablemodel.NoteTableModel;
import utils.EleviManager;
import utils.MateriiManager;
import utils.NoteManager;
import utils.ProfManager;

/**
 *
 * @author Dominic
 */
public class frmAdaugaNota extends javax.swing.JDialog {

    /**
     * Creates new form frmAdaugaNota
     *
     * @param other
     * @param modal
     */
    private MateriiManager materiiManager = new MateriiManager();
    private ProfManager pm = new ProfManager();
    private EleviManager em = new EleviManager();
    private NoteManager nm = new NoteManager();
    private NoteTableModel noteTableModel;

    public frmAdaugaNota(JDialog other, boolean modal) {
        super(other, modal);
        initComponents();
        DefaultComboBoxModel materiiModel = new DefaultComboBoxModel();
        materiiModel.addElement("--Selectati materia--");
        List<Materie> materii = materiiManager.getListaMaterii();
        for (Materie m : materii) {
            materiiModel.addElement(m);
        }

        cmbMaterie.setModel(materiiModel);
        DefaultComboBoxModel profesoriModel = new DefaultComboBoxModel();
        profesoriModel.addElement("--Selectati profesor--");
        List<Profesor> profesori = pm.getListaProfesori();
        for (Profesor p : profesori) {
            profesoriModel.addElement(p);
        }
        cmbProfesori.setModel(profesoriModel);
        DefaultComboBoxModel eleviModel = new DefaultComboBoxModel();
        eleviModel.addElement("--Selectati elev--");
        List<Elev> elevi = em.getListaElevi();
        for (Elev e : elevi) {
            eleviModel.addElement(e);
        }
        cmbElevi.setModel(eleviModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spinnerNota = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        cmbProfesori = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbMaterie = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbElevi = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adauga nota");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalii Nota"));

        jLabel1.setText("Nota :");

        spinnerNota.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel2.setText("Profesor :");

        cmbProfesori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Materie :");

        cmbMaterie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Elev :");

        cmbElevi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Data/Ora nota:");

        jDateChooser1.setDateFormatString("dd.MM.yyyy HH:mm:ss");

        jButton1.setText("Salveaza date");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbProfesori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbMaterie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbElevi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinnerNota, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 66, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spinnerNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbProfesori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbMaterie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbElevi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!valid()) {
            return;
        }
        Profesor p = (Profesor) cmbProfesori.getSelectedItem();
        Materie m = (Materie) cmbMaterie.getSelectedItem();
        Elev e = (Elev) cmbElevi.getSelectedItem();
        Date d = jDateChooser1.getDate();
        int nota = (int) spinnerNota.getValue();
        Nota n = new Nota(nota, m, d, e, p);
        nm.saveNota(n);
        JOptionPane.showMessageDialog(this, "Nota a fost salvata", "Salvare nota", JOptionPane.INFORMATION_MESSAGE);
        noteTableModel.adaugaNota(n);
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean valid() {
        if (cmbProfesori.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Va rog, selectati un profesor din lista", "Eroare profesor", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }

        if (cmbMaterie.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Va rog, selectati o materie din lista", "Eroare materie", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (cmbElevi.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Va rog, selectati un elev din lista", "Eroare elev", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (jDateChooser1.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Va rog, selectati data si ora ", "Eroare data", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }

        return true;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbElevi;
    private javax.swing.JComboBox cmbMaterie;
    private javax.swing.JComboBox cmbProfesori;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spinnerNota;
    // End of variables declaration//GEN-END:variables

    void setNoteTableModel(NoteTableModel noteTableModel1) {
        this.noteTableModel = noteTableModel1;
    }
}
