/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import beans.Materii;
import dao.MateriiDAO;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import obiecte.Materie;
import utils.MateriiManager;

/**
 *
 * @author Dominic
 */
public class frmAdaugaMaterie extends javax.swing.JDialog {

    /**
     * Creates new form frmAdaugaMaterie
     */
    
    private MateriiDAO materiiManager;
    private DefaultListModel df;
    private Materii materieSelectata;

    public void setDf(DefaultListModel df) {
        this.df = df;
    }

    public void setMaterieSelectata(Materii materieSelectata) {
        this.materieSelectata = materieSelectata;
    }

    public frmAdaugaMaterie(JDialog parent, boolean modal, Materii mSelectata,MateriiDAO materiiManager) {
        super(parent, modal);
        initComponents();
        this.materieSelectata = mSelectata;
        this.materiiManager=materiiManager;
        if(materieSelectata != null){
            System.out.println(materieSelectata.getId()+" selectata");
            txtNumeMaterie.setText(materieSelectata.getDenumire());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumeMaterie = new javax.swing.JTextField();
        btnAdaugaMaterie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adauga materie");

        jLabel1.setText("Nume materie:");

        btnAdaugaMaterie.setText("Salveaza materia");
        btnAdaugaMaterie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdaugaMaterieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(btnAdaugaMaterie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeMaterie, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeMaterie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(btnAdaugaMaterie, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdaugaMaterieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdaugaMaterieActionPerformed
        // TODO add your handling code here:
        
        if(!valid()){
            return;
        }
        
        String nume = txtNumeMaterie.getText();
        
        Materii mat = new Materii();
        mat.setDenumire(nume);
        if(materieSelectata!=null){
            mat.setId(materieSelectata.getId());
        }
        
        materiiManager.saveMaterie(mat);
        
        if(mat.getId()>0){
            df.setElementAt(mat, materiiManager.getMaterieIndexById(mat.getId()));
        }
        else{
            df.addElement(mat);
        }
        
        String info = "Materia a fost salvata";
        JOptionPane.showMessageDialog(this, info, "Super!", JOptionPane.INFORMATION_MESSAGE);
        
     //   txtNumeMaterie.setText("");
        
        txtNumeMaterie.requestFocusInWindow();
        txtNumeMaterie.selectAll();
        
    }//GEN-LAST:event_btnAdaugaMaterieActionPerformed

    public boolean valid(){
        String nume = txtNumeMaterie.getText().trim();
      //  String output = (nume.substring(0, 1).toUpperCase() + nume.substring(1)).trim();
        if(nume.length()<3){
            JOptionPane.showMessageDialog(this, "Numele materiei trebuie sa aiba minim 3 litere", "Eroare materie", JOptionPane.ERROR_MESSAGE);
            txtNumeMaterie.requestFocusInWindow();
            txtNumeMaterie.selectAll();
            return false;
        }
       if(materiiManager.isMaterieExists(nume.trim())){
            JOptionPane.showMessageDialog(this, "Aceasta materie exista deja in baza de date", "Eroare materie", JOptionPane.ERROR_MESSAGE);
            txtNumeMaterie.requestFocusInWindow();
            txtNumeMaterie.selectAll();
            return false;
        } 
        return true;
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdaugaMaterie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNumeMaterie;
    // End of variables declaration//GEN-END:variables
}
