/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import javax.swing.JOptionPane;
import obiecte.Absenta;
import utils.AbsenteManager;

/**
 *
 * @author Dominic
 */
public class frmAdministrareAbsente extends javax.swing.JDialog {

    /**
     * Creates new form frmAdministrareAbsente
     */
    
    private AbsenteManager am = new AbsenteManager();
    
    
    public frmAdministrareAbsente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        absenteTableModel1.setListaAbsente(am.getListaAbsente());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        absenteTableModel1 = new tablemodel.AbsenteTableModel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAbsente = new javax.swing.JTable();
        btnAdaugaAbsente = new javax.swing.JButton();
        btnStergeAbsente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrare absente");

        tableAbsente.setModel(absenteTableModel1);
        tableAbsente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableAbsente);

        btnAdaugaAbsente.setText("Adauga absente");
        btnAdaugaAbsente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdaugaAbsenteActionPerformed(evt);
            }
        });

        btnStergeAbsente.setText("Sterge absente");
        btnStergeAbsente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStergeAbsenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdaugaAbsente, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStergeAbsente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdaugaAbsente, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnStergeAbsente, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdaugaAbsenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdaugaAbsenteActionPerformed
        // TODO add your handling code here:
        
        frmAdaugaAbsenta frm=new frmAdaugaAbsenta(this,true);
        frm.setAbsenteTableModel(absenteTableModel1);
        frm.setLocationRelativeTo(this);
        frm.setVisible(true);
        
    }//GEN-LAST:event_btnAdaugaAbsenteActionPerformed

    private void btnStergeAbsenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStergeAbsenteActionPerformed
        int index=tableAbsente.convertRowIndexToModel(tableAbsente.getSelectedRow());
        if(index!=-1){
            System.out.println("Sterg de la index-ul "+index);
            int raspuns=JOptionPane.showConfirmDialog(this, "Sigur stergeti absenta ?", "Stergere absenta",JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE);
            if(raspuns==JOptionPane.YES_OPTION){
                Absenta a=absenteTableModel1.getAbsenta(index);
                am.removeAbsenta(a);
                absenteTableModel1.removeAbsenta(a);
                JOptionPane.showMessageDialog(this,"Absenta stearsa cu succes!");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Va rog selectati o absenta!", "Absenta neselectata", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnStergeAbsenteActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tablemodel.AbsenteTableModel absenteTableModel1;
    private javax.swing.JButton btnAdaugaAbsente;
    private javax.swing.JButton btnStergeAbsente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAbsente;
    // End of variables declaration//GEN-END:variables
}
