package beans;
// Generated Oct 13, 2015 7:57:49 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Absente generated by hbm2java
 */
public class Absente  implements java.io.Serializable {


     private int id;
     private Date dataAbsenta;
     private Integer idProfesor;
     private Integer idElev;
     private Integer idMaterie;
     private Boolean motivata;

    public Absente() {
    }

	
    public Absente(int id) {
        this.id = id;
    }
    public Absente(int id, Date dataAbsenta, Integer idProfesor, Integer idElev, Integer idMaterie, Boolean motivata) {
       this.id = id;
       this.dataAbsenta = dataAbsenta;
       this.idProfesor = idProfesor;
       this.idElev = idElev;
       this.idMaterie = idMaterie;
       this.motivata = motivata;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getDataAbsenta() {
        return this.dataAbsenta;
    }
    
    public void setDataAbsenta(Date dataAbsenta) {
        this.dataAbsenta = dataAbsenta;
    }
    public Integer getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(Integer idProfesor) {
        this.idProfesor = idProfesor;
    }
    public Integer getIdElev() {
        return this.idElev;
    }
    
    public void setIdElev(Integer idElev) {
        this.idElev = idElev;
    }
    public Integer getIdMaterie() {
        return this.idMaterie;
    }
    
    public void setIdMaterie(Integer idMaterie) {
        this.idMaterie = idMaterie;
    }
    public Boolean getMotivata() {
        return this.motivata;
    }
    
    public void setMotivata(Boolean motivata) {
        this.motivata = motivata;
    }




}


