package beans;
// Generated Oct 13, 2015 7:57:49 PM by Hibernate Tools 3.6.0



/**
 * Clase generated by hbm2java
 */
public class Clase  implements java.io.Serializable {


     private int id;
     private Integer numarClasa;
     private String literaClasa;

    public Clase() {
    }

	
    public Clase(int id) {
        this.id = id;
    }
    public Clase(int id, Integer numarClasa, String literaClasa) {
       this.id = id;
       this.numarClasa = numarClasa;
       this.literaClasa = literaClasa;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getNumarClasa() {
        return this.numarClasa;
    }
    
    public void setNumarClasa(Integer numarClasa) {
        this.numarClasa = numarClasa;
    }
    public String getLiteraClasa() {
        return this.literaClasa;
    }
    
    public void setLiteraClasa(String literaClasa) {
        this.literaClasa = literaClasa;
    }




}


