package beans;
// Generated Oct 13, 2015 7:57:49 PM by Hibernate Tools 3.6.0



/**
 * Materii generated by hbm2java
 */
public class Materii  implements java.io.Serializable {


     private int id;
     private String denumire;

    public Materii() {
    }

	
    public Materii(int id) {
        this.id = id;
    }
    public Materii(int id, String denumire) {
       this.id = id;
       this.denumire = denumire;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDenumire() {
        return this.denumire;
    }
    
    public void setDenumire(String denumire) {
        this.denumire = denumire;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Materii other = (Materii) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return denumire;
    }

    
    

    
    



}


