package beans;
// Generated Oct 13, 2015 7:57:49 PM by Hibernate Tools 3.6.0



/**
 * ProfesoriMaterii generated by hbm2java
 */
public class ProfesoriMaterii  implements java.io.Serializable {


     private int id;
     private Integer idProfesor;
     private Integer idMaterie;

    public ProfesoriMaterii() {
    }

	
    public ProfesoriMaterii(int id) {
        this.id = id;
    }
    public ProfesoriMaterii(int id, Integer idProfesor, Integer idMaterie) {
       this.id = id;
       this.idProfesor = idProfesor;
       this.idMaterie = idMaterie;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(Integer idProfesor) {
        this.idProfesor = idProfesor;
    }
    public Integer getIdMaterie() {
        return this.idMaterie;
    }
    
    public void setIdMaterie(Integer idMaterie) {
        this.idMaterie = idMaterie;
    }




}


